Gestao-Diarios/urls.py
from django.conf.urls import url

from . import views

app_name = 'coord'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^setup_diarios/$', views.setup_diarios, name='setup_diarios'),
    url(r'^setup_horarios/$', views.setup_horarios, name='setup_horarios'),
    url(r'^gerar_previstas/$', views.setup_aulas_previstas, name='gerar_previstas'),
    url(r'^gerar_previstas2/$', views.setup_aulas_previstas2, name='gerar_previstas2'),
    url(r'^inserir_aulas/$', views.setup_aulas_registradas, name='inserir_aulas'),
    url(r'^remove_aulas/$', views.remove_aulas, name='remove_aulas'),
    url(r'^extrair_dados/$', views.setup_extract_data, name='extrair_dados'),
    url(r'^clear_aulas/$', views.clear_aulas, name='clear_aulas'),
    url(r'^clear/$', views.clear_data, name='clear'),
    url(r'^(?P<disciplina_id>[0-9]+)/$', views.detail, name='detail'),
]

SIGA-IFPE-PALMARES/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^coord/', include('Gestao-Diarios.urls')),
    url(r'^admin/', admin.site.urls),
]

Gestao-Diarios/models.py
from django.db import models

class Curso(models.Model):
    nome = models.CharField(primary_key=True, max_length=120)
    def __str__(self):
        return self.nome

class Turma(models.Model):
    nome = models.CharField(primary_key=True, max_length=120)
    curso = models.ForeignKey(Curso, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.nome

class Professor(models.Model):
    nome = models.CharField(max_length=120)

    def __str__(self):
        return self.nome


class Disciplina(models.Model):
    nome = models.CharField(max_length=60)
    creditos = models.IntegerField(choices=((2, 2), (3,3), (4,4), (5,5)))
    turma = models.ForeignKey(Turma, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "%s - %s" % (str(self.turma), str(self.nome))

class Diario (models.Model):
    numero = models.CharField(primary_key=True, max_length=10)
    curso = models.ForeignKey(Curso, null=True, on_delete=models.SET_NULL)
    professor = models.ForeignKey(Professor, null=True, on_delete=models.SET_NULL)
    disciplina = models.OneToOneField(Disciplina, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "%s - %s" % (self.numero, self.disciplina)

DAYS_OF_WEEK = (
    (0, 'Segunda'),
    (1, 'Terca'),
    (2, 'Quarta'),
    (3, 'Quinta'),
    (4, 'Sexta'),
    (5, 'Sabado'),
    (6, 'Domingo'),
)

class Feriado(models.Model):
    data = models.DateField()
    descricao = models.CharField(max_length=240)

    def __str__(self):
        return "%s - %s" % (str(self.data), self.descricao)

class HorarioAula(models.Model):
    dia = models.CharField(max_length=1, choices=DAYS_OF_WEEK)
    numero_de_aulas = models.IntegerField(default=0)
    diario = models.ForeignKey(Diario, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "%s - %d" % (DAYS_OF_WEEK[int(self.dia)][1], self.numero_de_aulas)

class Aula(models.Model):
    diario = models.ForeignKey(Diario, on_delete=models.CASCADE)
    data = models.DateField()
    prevista = models.BooleanField(default=False)
    registrada = models.BooleanField(default=False)
    resolvido = models.BooleanField(default=False)
    numero_de_aulas_prevista = models.IntegerField(default=0)
    numero_de_aulas = models.IntegerField(default=0)

    def __str__(self):
        return "%s - %s - %s" % (str(self.data), str(self.numero_de_aulas_prevista), self.diario)

Gestao-Diarios/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
import os
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings
from datetime import datetime
from django.utils.encoding import smart_str

from .models import *
from . import setup

def index(request):
    list_disciplinas = Disciplina.objects.order_by('-id')[:5]
    context = {
        'list_disciplinas': list_disciplinas
    }
    return render(request, 'Gestao-Diarios/index.html', context)

def detail(request, disciplina_id):
    disciplina = get_object_or_404(Disciplina, pk=disciplina_id)
    return render(request, 'Gestao-Diarios/detail.html', {'disciplina': disciplina})

def setup_diarios(request):
    file = request.FILES['myfile']
    path = default_storage.save('tmp/file_diarios.pdf', ContentFile(file.read()))
    tmp_file = os.path.join(settings.MEDIA_ROOT, path)
    file = open(tmp_file, "rb")
    setup.setup_diarios(file)
    return HttpResponse("Ok")

def setup_horarios(request):
    file = request.FILES['myfile']
    path = default_storage.save('tmp/file_horarios.txt', ContentFile(file.read()))
    tmp_file = os.path.join(settings.MEDIA_ROOT, path)
    file = open(tmp_file)
    setup.setup_horarios(file)
    return HttpResponse("Ok")

def setup_aulas_registradas(request):
    file = request.FILES['myfile']
    path = default_storage.save('tmp/file_aulas.pdf', ContentFile(file.read()))
    tmp_file = os.path.join(settings.MEDIA_ROOT, path)
    file = open(tmp_file, "rb")
    setup.setup_aulas_ministradas(file)
    return HttpResponse("Ok")

def setup_aulas_previstas(request):
    format = "%Y-%m-%d"
    setup.setup_aulas_previstas(datetime.strptime(request.GET["data_inicio"], format), int(request.GET["semanas"]))
    return HttpResponse("Ok")

def setup_aulas_previstas2(request):
    format = "%Y-%m-%d"
    setup.setup_aulas_previstas2(datetime.strptime(request.GET["data_inicio"], format), datetime.strptime(request.GET["data_fim"], format))
    return HttpResponse("Ok")

def setup_extract_data(request):
    file = request.FILES['myfile']
    path = default_storage.save('tmp/file_aulas.txt', ContentFile(file.read()))
    tmp_file = os.path.join(settings.MEDIA_ROOT, path)
    file = open(tmp_file, encoding="utf8")
    report = setup.extract_data(file)

    file_name = "data.csv"
    path_to_file = os.path.join(settings.MEDIA_ROOT, "tmp/" + file_name)
    file_result = open(path_to_file, 'w+')
    file_result.write(report)
    file_result.close()

    if os.path.exists(path_to_file):
        with open(path_to_file, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(path_to_file)
            return response
    raise HttpResponse("error")

def remove_aulas(request):
    format = "%Y-%m-%d"
    data = datetime.strptime(request.GET["data"], format)
    Aula.objects.filter(data=data).delete()
    return HttpResponse("Ok")

def clear_aulas(request):
    Aula.objects.all().delete()
    return HttpResponse("Ok")

def clear_data(request):
    Turma.objects.all().delete()
    Professor.objects.all().delete()
    Disciplina.objects.all().delete()
    Diario.objects.all().delete()
    HorarioAula.objects.all().delete()
    Aula.objects.all().delete()
    return HttpResponse("Ok")

Gestao-Diarios/templates/Gestao-Diarios/detail.html
{{ disciplina }}

Gestao-Diarios/templates/Gestao-Diarios/index.html
<h1>Inserir dados de Diarios</h1>
<form action="{% url 'coord:setup_diarios' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" />
    <input type="submit" value="Start">
</form>
<h1>Inserir dados de Horários</h1>
<form action="{% url 'coord:setup_horarios' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" />
    <input type="submit" value="Start">
</form>
<h1>Inserir Aulas</h1>
<form action="{% url 'coord:inserir_aulas' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" />
    <input type="submit" value="Start">
</form>
<h1>Gerar aulas previstas</h1>
<form action="{% url 'coord:gerar_previstas' %}">
    <input type="date" name="data_inicio">
    <input type="number" name="semanas">
    <input type="submit" value="Gerar">
</form>
<form action="{% url 'coord:gerar_previstas2' %}">
    <input type="date" name="data_inicio">
    <input type="date" name="data_fim">
    <input type="submit" value="Gerar">
</form>
<h1>Extrair dados</h1>
<form action="{% url 'coord:extrair_dados' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" />
    <input type="submit" value="Extrair">
</form>
<h1>Remover Aulas</h1>
<form action="{% url 'coord:remove_aulas' %}">
    <input type="date" name="data">
    <input type="submit" value="Remover">
</form>
<h1>Apagar todos os dados</h1>
<form action="{% url 'coord:clear_aulas' %}">
    <input type="submit" value="Apagar Aulas">
</form>
<h1>Apagar todos os dados</h1>
<form action="{% url 'coord:clear' %}">
    <input type="submit" value="Clear All">
</form>